# Generated by Django 4.1 on 2022-08-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppMobile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='advantage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='disadvantage',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='os',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppMobile.os'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m'),
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppMobile.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category_products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppMobile.categoryproduct'),
        ),
    ]
