# Generated by Django 4.1.2 on 2022-11-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.ManyToManyField(blank=True, to='AppMobile.memory'),
        ),
    ]
