# Generated by Django 4.1.2 on 2022-10-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMobile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='content_comment',
        ),
    ]
