# Generated by Django 4.1.2 on 2022-10-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMobile', '0002_rename_content_comment_content_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content_comment',
            new_name='content',
        ),
    ]
