# Generated by Django 4.1 on 2022-08-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMobile', '0002_remove_product_advantage_remove_product_disadvantage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
