# Generated by Django 4.1.2 on 2022-10-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMobile', '0003_rename_content_comment_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
