# Generated by Django 4.0.2 on 2022-09-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppMobile', '0003_productview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productview',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppMobile.product'),
        ),
    ]
