# Generated by Django 4.1.2 on 2022-11-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMobile', '0005_comment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='province',
        ),
        migrations.RemoveField(
            model_name='productcode',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productcode',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='productcode',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productstorecode',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productstorecode',
            name='district',
        ),
        migrations.RemoveField(
            model_name='productstorecode',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productstorecode',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='productstorecode',
            name='province',
        ),
        migrations.RemoveField(
            model_name='productstorecode',
            name='store',
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='store',
            name='district',
        ),
        migrations.RemoveField(
            model_name='store',
            name='province',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='ProductCode',
        ),
        migrations.DeleteModel(
            name='ProductStoreCode',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
