# Generated by Django 4.1.2 on 2022-11-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMobile', '0006_remove_district_province_remove_productcode_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
